// lib/dict/menu/adminPages.ts
export const adminPages = {
  vi: {
    accounts: {
      title: "Quản lý tài khoản và hồ sơ",
      subtitle: "Phân quyền truy cập, quản lý hồ sơ và theo dõi hoạt động người dùng",
      tabs: {
        accounts: "Tài khoản",
        profiles: "Hồ sơ",
      },
      buttons: {
        createAccount: "Tạo tài khoản mới",
        createParent: "Tạo tài khoản phụ huynh",
        createStudent: "Tạo hồ sơ học viên",
      },
      stats: {
        totalAccounts: "Tổng tài khoản",
        active: "Đang hoạt động",
        twoFactor: "Bật xác thực 2 lớp",
        new: "Tài khoản mới",
        subtitle: {
          total: "Toàn hệ thống",
          active: "Truy cập thường xuyên",
          twoFactor: "Bảo mật cao",
          new: "30 ngày gần đây",
        },
      },
      filters: {
        all: "Tất cả",
        allStatus: "Tất cả trạng thái",
        allRoles: "Tất cả vai trò",
        admin: "Quản trị",
        teacher: "Giáo viên",
        parent: "Phụ huynh",
        staff: "Nhân viên",
        active: "Đang hoạt động",
        inactive: "Không hoạt động",
        search: "Tìm kiếm tên, email, số điện thoại...",
        perPage: "/ trang",
      },
      table: {
        title: "Danh sách tài khoản",
        accounts: "tài khoản",
        user: "Người dùng",
        contact: "Thông tin liên hệ",
        role: "Vai trò",
        status: "Trạng thái",
        lastLogin: "Lần đăng nhập cuối",
        actions: "Thao tác",
        createdDate: "Tạo ngày",
        notUpdated: "Chưa cập nhật",
        column: {
          5: "5 hàng",
          10: "10 hàng",
          20: "20 hàng",
          50: "50 hàng",
        },
      },
      roles: {
        admin: "Quản trị",
        teacher: "Giáo viên",
        parent: "Phụ huynh",
        managementStaff: "Nhân viên quản lý",
      },
      loading: "Đang tải dữ liệu...",
      error: "Không thể tải dữ liệu",
      retry: "Thử lại",
      status: {
        active: "Đang hoạt động",
        inactive: "Tạm khóa",
        enabled2FA: "Bật 2FA",
        disabled2FA: "Chưa bật",
      },
      userStatus: {
        notLoggedIn: "Chưa đăng nhập",
        lastLogin: "Đăng nhập",
        notActivated: "Chưa kích hoạt",
        loggedIn: "Đã đăng nhập",
        awaitingActivation: "Đang chờ kích hoạt",
        lastActivity: "Hoạt động gần nhất",
      },
      actions: {
        viewDetails: "Xem chi tiết",
        edit: "Chỉnh sửa",
        delete: "Xóa",
        activate: "Kích hoạt",
        deactivate: "Vô hiệu hóa",
      },
      messages: {
        success: "Thành công",
        createAccountSuccess: "Tạo tài khoản thành công",
        updateAccountSuccess: "Cập nhật tài khoản thành công",
        deleteAccountSuccess: "Xóa tài khoản thành công",
        error: "Lỗi",
        createAccountError: "Không thể tạo tài khoản",
        updateAccountError: "Không thể cập nhật tài khoản",
        deleteAccountError: "Không thể xóa tài khoản",
        notFound: "Chưa có",
        notLoggedIn: "Chưa đăng nhập",
      },
    },
    profiles: {
      stats: {
        totalProfiles: "Tổng hồ sơ",
        systemWide: "Toàn hệ thống",
        parents: "Phụ huynh",
        hasAccount: "Có tài khoản đăng nhập",
        students: "Học viên",
        linkedWithParent: "Đã liên kết phụ huynh",
        active: "Hồ sơ hoạt động",
        activeSubtitle: "Đang hoạt động",
        pendingApproval: "Hồ sơ chờ duyệt",
        locked: "Hồ sơ đang khóa",
      },
      filters: {
        all: "Tất cả",
        parents: "Phụ huynh",
        students: "Học viên",
        allApprovals: "Tất cả duyệt",
        pending: "Chờ duyệt",
        approved: "Đã duyệt",
        approveSelected: "Duyệt đã chọn",
        search: "Tìm kiếm theo tên, email...",
        perPage: "/ trang",
      },
      table: {
        type: "Loại",
        displayName: "Tên hiển thị",
        email: "Email",
        userId: "User ID",
        status: "Trạng thái",
        createdDate: "Ngày tạo",
        actions: "Hành động",
        selectAll: "Chọn tất cả hồ sơ chờ duyệt trong trang",
        selectProfile: "Chọn hồ sơ này",
        profileApproved: "Hồ sơ đã duyệt",
        active: "Đang hoạt động",
        locked: "Tạm khóa",
        pendingApproval: "Chờ duyệt",
        approved: "Đã duyệt",
        noProfiles: "Không có hồ sơ nào",
        createNewProfile: "Hãy tạo hồ sơ mới để bắt đầu",
      },
      actions: {
        viewDetails: "Xem chi tiết",
        viewLinkedStudents: "Xem học sinh đã liên kết",
        approveProfile: "Duyệt hồ sơ",
        reactivateProfile: "Kích hoạt lại hồ sơ",
        delete: "Xóa",
      },
      modals: {
        confirmDelete: "Xác nhận khóa hồ sơ",
        deleteMessage: "Bạn có chắc chắn muốn khóa hồ sơ \"{name}\"?",
        confirmApprove: "Xác nhận duyệt hồ sơ",
        approveSingleMessage: "Bạn có chắc chắn muốn duyệt hồ sơ \"{name}\"?",
        approveMultipleMessage: "Bạn có chắc chắn muốn duyệt {count} hồ sơ đã chọn?",
        confirmReactivate: "Xác nhận kích hoạt lại hồ sơ",
        reactivateMessage: "Bạn có chắc chắn muốn kích hoạt lại hồ sơ \"{name}\"?",
        delete: "Khóa",
        approve: "Duyệt hồ sơ",
        reactivate: "Kích hoạt lại",
        cancel: "Hủy",
      },
      pagination: {
        showing: "Hiển thị",
        of: "trong tổng số",
        profiles: "hồ sơ",
        selected: "Đã chọn",
      },
    },
    dashboard: {
      header: {
        title: "Tổng quan vận hành",
        subtitle: "Dữ liệu thời gian thực về lead, học viên, doanh thu và hiệu suất",
        month: "Tháng",
        refreshData: "Làm mới dữ liệu",
      },
      controlPanel: {
        title: "Bảng điều khiển quản trị",
        subtitle: "Tổng hợp dữ liệu vận hành theo thời gian thực, tối ưu cho theo dõi nhanh.",
        dateRange: "Khoảng thời gian",
        refresh: "Làm mới",
        last7Days: "7 ngày gần nhất",
        last30Days: "30 ngày gần nhất",
        last90Days: "90 ngày gần nhất",
      },
      tabs: {
        overview: "Overview",
        leads: "Leads",
        academic: "Academic",
        hr: "HR",
      },
      sections: {
        kpiOverview: "Tổng quan KPI",
        kpiSubtitle: "Các chỉ số trọng tâm toàn hệ thống",
        leadsAndPlacement: "Leads & Placement Test",
        leadsSubtitle: "Theo dõi hiệu quả tuyển sinh và xếp lớp",
        academic: "Học vụ",
        academicSubtitle: "Điểm danh, bài tập, nghỉ phép, tín chỉ bù",
        hr: "Nhân sự (HR)",
        hrSubtitle: "Cơ cấu nhân sự và bảng lương",
      },
      kpis: {
        totalStudents: "Tổng học viên",
        activeEnrollments: "Ghi danh đang hoạt động",
        totalLeads: "Tổng lead",
        attendanceRate: "Tỷ lệ điểm danh",
        conversionRate: "Tỷ lệ chuyển đổi",
        good: "Mức tốt",
        needsImprovement: "Cần cải thiện",
        newLeads: "Lead mới",
        enrolledLeads: "Lead đã ghi danh",
        submissionRate: "Tỷ lệ nộp bài",
        gradedRate: "Tỷ lệ chấm bài",
        leaveRequests: "Đơn nghỉ phép",
        totalStaff: "Tổng nhân sự",
        teachers: "Giáo viên",
        management: "Quản lý",
        admin: "Quản trị",
        totalPayroll: "Tổng lương",
        totalTests: "Tổng bài test",
        completed: "Hoàn thành",
        noShow: "Không tham dự",
        completionRate: "Tỷ lệ hoàn thành",
      },
      charts: {
        leadsByStatus: "Lead theo trạng thái",
        attendanceStatus: "Trạng thái điểm danh",
        enrollmentStatus: "Trạng thái ghi danh",
        placementTests: "Placement test theo trạng thái",
        leadsStatus: "Trạng thái lead",
        attendanceDetails: "Điểm danh",
        homeworkProgress: "Bài tập theo tiến độ (Bar)",
        leaveByStatus: "Nghỉ phép theo trạng thái",
        makeupCredits: "Tín chỉ bù theo trạng thái",
        placementCompletion: "Placement test hoàn thành",
        staffStructure: "Cơ cấu nhân sự (Bar)",
        payrollStatus: "Trạng thái payroll run",
        hrTrend: "Xu hướng vận hành HR",
        conversion: "Chuyển đổi",
        rate: "Tỷ lệ",
        active: "Đang hoạt động",
      },
      metrics: {
        assigned: "Đã giao",
        submitted: "Đã nộp",
        graded: "Đã chấm",
        missing: "Thiếu",
        workingHours: "Giờ làm",
        avgHours: "Giờ TB",
        payrollProcessed: "Xử lý lương",
        payrollPending: "Chờ xử lý",
      },
      empty: "Không có dữ liệu",
      liveView: "Live view",
      loading: "Đang làm mới dữ liệu...",
      reload: "Tải lại",
      students: "Học viên",
      leads: "Lead",
      attendance: "Điểm danh",
      accountant: "Kế toán",
    },
    classes: {
      header: {
        title: "Quản lý lớp học",
        subtitle: "Quản lý tạo lớp, lịch học, giáo viên, học viên và theo dõi hiệu suất lớp học",
      },
      stats: {
        totalClasses: "Tổng lớp học",
        ongoing: "Đang học",
        upcoming: "Sắp khai giảng",
        completed: "Đã kết thúc",
        totalStudents: "Tổng học viên",
      },
      buttons: {
        createClass: "Tạo lớp học mới",
        addStudent: "Thêm học viên",
        close: "Đóng",
        cancel: "Hủy bỏ",
        save: "Lưu thay đổi",
        add: "Thêm vào lớp",
        edit: "Chỉnh sửa",
        endClass: "Kết thúc lớp học",
        selectAll: "Chọn tất cả",
        deselectAll: "Bỏ chọn tất cả",
        submit: "Xác nhận",
        deleteSchedule: "Xóa lịch học",
        confirmDelete: "Xác nhận xóa",
      },
      form: {
        classCode: "Mã lớp",
        className: "Tên lớp",
        branch: "Chi nhánh",
        program: "Chương trình",
        mainTeacher: "Giáo viên chính",
        assistantTeacher: "Giáo viên phụ",
        maxCapacity: "Sĩ số tối đa",
        startDate: "Ngày bắt đầu",
        endDate: "Ngày kết thúc",
        schedule: "Lịch học",
        room: "Phòng học",
        description: "Mô tả lớp học",
        status: "Trạng thái",
        requiredField: "Trường bắt buộc",
      },
      schedule: {
        days: "Ngày học",
        time: "Thời gian",
        customTime: "Thời gian tùy chỉnh",
        sessionsPerWeek: "Buổi/tuần",
        selectDays: "Chọn ngày",
        selectTimeSlot: "Chọn khung giờ",
        totalSessions: "Tổng buổi học",
        noSchedule: "Chưa có lịch",
        viewSchedule: "Xem lịch",
        startTime: "Giờ bắt đầu",
        endTime: "Giờ kết thúc",
        morning: "Sáng (08:00 - 10:00)",
        afternoon: "Trưa (10:00 - 12:00)",
        earlyEvening: "Chiều (14:00 - 16:00)",
        lateEvening: "Chiều tối (16:00 - 18:00)",
        night: "Tối (18:00 - 20:00)",
        lateNight: "Tối muộn (19:30 - 21:30)",
        sessionsPerWeek2: "2 buổi/tuần",
        sessionsPerWeek3: "3 buổi/tuần",
        monday: "Thứ 2",
        tuesday: "Thứ 3",
        wednesday: "Thứ 4",
        thursday: "Thứ 5",
        friday: "Thứ 6",
        saturday: "Thứ 7",
        sunday: "Chủ nhật",
      },
      status: {
        active: "Đang học",
        upcoming: "Sắp khai giảng",
        completed: "Đã kết thúc",
      },
      table: {
        classCode: "Mã lớp",
        className: "Tên lớp",
        program: "Chương trình",
        teacher: "Giáo viên",
        branch: "Chi nhánh",
        enrollment: "Sĩ số",
        schedule: "Lịch học",
        status: "Trạng thái",
        actions: "Thao tác",
        noClasses: "Không tìm thấy lớp học",
        search: "Tìm kiếm lớp học...",
        allStatus: "Tất cả trạng thái",
        allTeachers: "Tất cả giáo viên",
      },
      modal: {
        addStudents: "Thêm học viên",
        selectStudents: "Chọn học viên để thêm vào lớp",
        searchPlaceholder: "Tìm kiếm học viên...",
        noStudents: "Không tìm thấy học viên",
        loading: "Đang tải...",
        selected: "Đã chọn",
        total: "Tổng",
        students: "học viên",
        remainingSlots: "Sĩ số còn lại",
        capacityExceeded: "Không thể chọn thêm học viên",
        capacityExceededDesc: "Sĩ số còn lại của lớp chỉ là",
        addSuccess: "Thêm học viên thành công",
        addSuccessDesc: "Đã thêm {count} học viên vào lớp",
        addFailed: "Thêm học viên thất bại",
        addFailedDesc: "Không thể thêm: {students}",
        addError: "Đã xảy ra lỗi khi thêm học viên. Vui lòng thử lại.",
        overCapacity: "Vượt quá sĩ số! Lớp sẽ có {count} học viên (tối đa {capacity})",
        capacityOK: "Đã chọn {count} / Sĩ số còn lại: {remaining}",
      },
      validation: {
        codeRequired: "Mã lớp không được bỏ trống",
        codeExists: "Mã lớp {code} đã tồn tại",
        nameRequired: "Tên lớp không được bỏ trống",
        nameExists: "Lớp {name} đã tồn tại",
        programRequired: "Vui lòng chọn chương trình",
        branchRequired: "Vui lòng chọn chi nhánh",
        teacherRequired: "Vui lòng chọn giáo viên chính",
        assistantTeacherConflict: "Giáo viên phụ và giáo viên chính không được trùng nhau",
        capacityRequired: "Sĩ số tối đa không được bỏ trống",
        capacityMin: "Sĩ số tối đa phải ≥ 1",
        startDateRequired: "Ngày bắt đầu không được bỏ trống",
        scheduleRequired: "Lịch học không được bỏ trống",
        roomRequired: "Phòng học không được bỏ trống",
        roomConflict: "Phòng {room} bị xung đột lịch học",
        sessionCountError: "Không thể tính toán số buổi học",
      },
      messages: {
        createSuccess: "Tạo lớp học thành công",
        updateSuccess: "Cập nhật lớp học thành công",
        updateFailed: "Cập nhật lớp học thất bại",
        createFailed: "Không thể tạo lớp học. Vui lòng thử lại.",
        deleteConfirm: "Bạn có chắc chắn muốn kết thúc lớp học này?",
        endClassSuccess: "Kết thúc lớp học thành công",
        endClassFailed: "Không thể kết thúc lớp học",
        invalidStatusTransition: "Không thể chuyển trạng thái lớp học",
        fromUpcomingToOngoing: "Không thể chuyển trạng thái lớp từ sắp khai giảng sang đang học",
        fromOngoingToCompleted: "Không thể chuyển trạng thái lớp từ đang học sang kết thúc",
        error: "Đã xảy ra lỗi. Vui lòng thử lại.",
      },
    },
    courses: {
      header: {
        title: "Quản trị chương trình học",
        subtitle: "Quản lý danh mục chương trình học theo toàn hệ thống và chi nhánh",
      },
      buttons: {
        create: "Tạo chương trình mới",
        view: "Xem chi tiết",
        edit: "Sửa",
        assignBranch: "Gán chi nhánh",
        cancel: "Hủy bỏ",
        reset: "Đặt lại",
        restore: "Khôi phục",
        save: "Lưu thay đổi",
        close: "Đóng",
      },
      stats: {
        totalCourses: "Tổng chương trình",
        active: "Đang hoạt động",
        totalStudents: "Tổng học viên",
        monthlyRevenue: "Doanh thu/tháng",
      },
      filters: {
        branchFiltered: "Đang lọc theo chi nhánh đã chọn",
        search: "Tìm kiếm chương trình học...",
        statusLabel: "Chọn trạng thái",
        allStatus: "Tất cả trạng thái",
        active: "Đang hoạt động",
        paused: "Tạm dừng",
      },
      table: {
        title: "Danh sách chương trình học",
        courseName: "Tên chương trình",
        duration: "Thời lượng",
        fee: "Học phí",
        branch: "Chi nhánh sử dụng",
        status: "Trạng thái",
        actions: "Thao tác",
        count: "chương trình",
        notFound: "Không tìm thấy chương trình học",
        tryFilter: "Thử thay đổi bộ lọc hoặc tạo chương trình mới",
        showing: "Hiển thị",
        to: "tới",
        outOf: "trong tổng số",
      },
      modal: {
        createTitle: "Tạo chương trình mới",
        updateTitle: "Cập nhật chương trình",
        createSubtitle: "Chương trình là tài nguyên dùng chung — sau khi tạo, gán vào các chi nhánh riêng biệt",
        updateSubtitle: "Chỉnh sửa thông tin chương trình học",
        branchLabel: "Chi nhánh",
        branchRequired: "Chi nhánh *",
        courseNameLabel: "Tên chương trình",
        courseNameRequired: "Tên chương trình *",
        courseNamePlaceholder: "VD: Tiếng Anh giao tiếp cơ bản",
        programTypeLabel: "Loại chương trình",
        programTypeDesc: "Chương trình chính là mặc định. Có thể đánh dấu phụ trợ hoặc bù, nhưng không được bật đồng thời cả hai.",
        supplementary: "Đánh dấu chương trình phụ trợ",
        supplementaryLabel: "Chương trình phụ trợ",
        makeup: "Đánh dấu chương trình bù",
        makeupLabel: "Chương trình bù",
        programTypeInfo: "Bên trái là chương trình phụ trợ, bên phải là chương trình bù. Nếu không chọn ô nào, hệ thống sẽ tạo chương trình chính.",
        programTypeSelected: "Loại đang chọn:",
        programMain: "Chương trình chính",
        leaveLimitTitle: "Giới hạn nghỉ ngắn ngày theo tháng",
        leaveLimitDesc: "Cấu hình này dùng cho leave request theo chương trình. Khi bạn đổi số buổi nghỉ, chỉ các lớp tạo mới từ chương trình này mới áp dụng, còn các lớp đã tạo trước đó sẽ giữ giới hạn cũ.",
        leaveLimitLabel: "Số buổi nghỉ tối đa / tháng",
        leaveLimitPlaceholder: "VD: 3 (để trống nếu chưa cấu hình)",
        leaveCurrentLimit: "Giới hạn hiện tại",
        saveLeaveLimit: "Lưu giới hạn",
        selectBranchPlaceholder: "Chọn chi nhánh",
        assignBranchTitle: "Gán chi nhánh vào chương trình",
        assignBranchSubtitle: "Một chương trình có thể được gán vào nhiều chi nhánh khác nhau",
        assignBranchLabel: "Chọn chi nhánh cần gán",
      },
      validation: {
        missingInfo: "Thiếu thông tin",
        selectBranch: "Vui lòng chọn chi nhánh",
        cannotBothTypes: "Chương trình không thể vừa là bù vừa là phụ trợ",
        invalidLeaveLimit: "Giá trị chưa hợp lệ",
        invalidLeaveValue: "Số buổi nghỉ tối đa trong tháng phải lớn hơn 0.",
        nameRequired: "Tên chương trình là bắt buộc",
        selectBranchForAssign: "Vui lòng chọn chi nhánh cần gán",
      },
      messages: {
        success: "Thành công",
        error: "Lỗi",
        courseCreated: "Đã tạo chương trình",
        courseUpdated: "Đã cập nhật chương trình",
        createFailed: "Không thể tạo chương trình. Vui lòng thử lại.",
        updateFailed: "Không thể cập nhật chương trình. Vui lòng thử lại.",
        toggleSuccess: "Đã thay đổi trạng thái chương trình thành công",
        toggleFailed: "Không thể thay đổi trạng thái chương trình. Vui lòng thử lại.",
        notFoundDetail: "Không thể tải thông tin chi tiết chương trình.",
        leaveLimitUpdated: "Đã cập nhật giới hạn nghỉ",
        leaveLimitUpdateNote: "Chỉ các lớp được tạo mới sau thay đổi này mới nhận giới hạn nghỉ mới.",
        pauseConfirm: "Xác nhận tạm dừng chương trình",
        pauseConfirmMsg: "Bạn có chắc chắn muốn tạm dừng chương trình \"{name}\"? Chương trình sẽ không còn hoạt động sau khi tạm dừng.",
        activateConfirm: "Xác nhận kích hoạt chương trình",
        activateConfirmMsg: "Bạn có chắc chắn muốn kích hoạt chương trình \"{name}\"? Chương trình sẽ được kích hoạt và có thể sử dụng ngay.",
        saving: "Đang lưu...",
        assignBranchSuccess: "Đã gán chi nhánh thành công",
        assignBranchFailed: "Không thể gán chi nhánh. Vui lòng thử lại.",
      },
      details: {
        title: "Chi tiết chương trình",
        subtitle: "Thông tin chi tiết về chương trình học",
        nameLabel: "Tên chương trình",
        descLabel: "Mô tả chương trình",
        sessionsLabel: "Số buổi học",
        tuitionLabel: "Học phí mặc định",
        unitPriceLabel: "Giá mỗi buổi",
        branchLabel: "Chi nhánh đang sử dụng",
        branchAssignmentsLabel: "Các chi nhánh sử dụng chương trình này",
        noBranchAssignments: "Chưa gán vào chi nhánh nào",
        typeLabel: "Loại chương trình",
        statusLabel: "Trạng thái",
        noInfo: "Chưa có thông tin",
        noDescription: "Chưa có mô tả",
        noBranch: "Chưa có chi nhánh",
        defaultMakeupClass: "Lớp bù mặc định",
      },
      status: {
        active: "Đang hoạt động",
        paused: "Tạm dừng",
        main: "Chương trình chính",
        supplementary: "Chương trình phụ trợ",
        makeup: "Chương trình bù",
      },
      types: {
        main: "Chính",
        supplementary: "Phụ trợ",
        makeup: "Bù",
      },
    },
  },
  en: {
    accounts: {
      title: "Account & Profile Management",
      subtitle: "Manage access permissions, profiles and monitor user activity",
      tabs: {
        accounts: "Accounts",
        profiles: "Profiles",
      },
      buttons: {
        resetPassword: "Reset Password",
        createAccount: "Create New Account",
        createParent: "Create Parent Account",
        createStudent: "Create Student Profile",
      },
      stats: {
        totalAccounts: "Total Accounts",
        active: "Active",
        twoFactor: "2FA Enabled",
        new: "New Accounts",
        subtitle: {
          total: "System-wide",
          active: "Frequent access",
          twoFactor: "High security",
          new: "Last 30 days",
        },
      },
      filters: {
        all: "All",
        allStatus: "All Status",
        allRoles: "All Roles",
        admin: "Admin",
        teacher: "Teacher",
        parent: "Parent",
        staff: "Staff",
        active: "Active",
        inactive: "Inactive",
        search: "Search by name, email, phone...",
        perPage: "/ page",
      },
      table: {
        title: "Account List",
        accounts: "accounts",
        user: "User",
        contact: "Contact Info",
        role: "Role",
        status: "Status",
        lastLogin: "Last Login",
        actions: "Actions",
        createdDate: "Created Date",
        notUpdated: "Not updated",
        column: {
          5: "5 rows",
          10: "10 rows",
          20: "20 rows",
          50: "50 rows",
        },
      },
      roles: {
        admin: "Administrator",
        teacher: "Teacher",
        parent: "Parent",
        managementStaff: "Management Staff",
      },
      loading: "Loading data...",
      error: "Unable to load data",
      retry: "Try Again",
      status: {
        active: "Active",
        inactive: "Inactive",
        enabled2FA: "2FA Enabled",
        disabled2FA: "Not Enabled",
      },
      userStatus: {
        notLoggedIn: "Not logged in",
        lastLogin: "Last login",
        notActivated: "Not activated",
        loggedIn: "Logged in",
        awaitingActivation: "Awaiting activation",
        lastActivity: "Last activity",
      },
      actions: {
        viewDetails: "View details",
        edit: "Edit",
        resetPassword: "Reset password",
        delete: "Delete",
        activate: "Activate",
        deactivate: "Deactivate",
      },
      messages: {
        success: "Success",
        createAccountSuccess: "Account created successfully",
        updateAccountSuccess: "Account updated successfully",
        deleteAccountSuccess: "Account deleted successfully",
        error: "Error",
        createAccountError: "Unable to create account",
        updateAccountError: "Unable to update account",
        deleteAccountError: "Unable to delete account",
        notFound: "Not available",
        notLoggedIn: "Not logged in",
      },
    },
    profiles: {
      stats: {
        totalProfiles: "Total Profiles",
        systemWide: "System-wide",
        parents: "Parents",
        hasAccount: "Have login account",
        students: "Students",
        linkedWithParent: "Linked to Parent",
        active: "Profiles Active",
        activeSubtitle: "Active",
        pendingApproval: "Profile Pending Approval",
        locked: "Profile Locked",
      },
      filters: {
        all: "All",
        parents: "Parents",
        students: "Students",
        allApprovals: "All approvals",
        pending: "Pending",
        approved: "Approved",
        approveSelected: "Approve selected",
        search: "Search by name, email...",
        perPage: "/ page",
      },
      table: {
        type: "Type",
        displayName: "Display Name",
        email: "Email",
        userId: "User ID",
        status: "Status",
        createdDate: "Created Date",
        actions: "Actions",
        selectAll: "Select all pending profiles on this page",
        selectProfile: "Select this profile",
        profileApproved: "Profile approved",
        active: "Active",
        locked: "Locked",
        pendingApproval: "Pending approval",
        approved: "Approved",
        noProfiles: "No profiles found",
        createNewProfile: "Create a new profile to get started",
      },
      actions: {
        viewDetails: "View details",
        viewLinkedStudents: "View linked students",
        approveProfile: "Approve profile",
        reactivateProfile: "Reactivate profile",
        delete: "Delete",
      },
      modals: {
        confirmDelete: "Confirm lock profile",
        deleteMessage: "Are you sure you want to lock the profile \"{name}\"?",
        confirmApprove: "Confirm approve profile",
        approveSingleMessage: "Are you sure you want to approve profile \"{name}\"?",
        approveMultipleMessage: "Are you sure you want to approve {count} selected profiles?",
        confirmReactivate: "Confirm reactivate profile",
        reactivateMessage: "Are you sure you want to reactivate profile \"{name}\"?",
        delete: "Lock",
        approve: "Approve profile",
        reactivate: "Reactivate",
        cancel: "Cancel",
      },
      pagination: {
        showing: "Showing",
        of: "of",
        profiles: "profiles",
        selected: "Selected",
      },
    },
    dashboard: {
      header: {
        title: "Overall Operations",
        subtitle: "Real-time data about leads, students, revenue and performance",
        month: "Month",
        refreshData: "Refresh Data",
      },
      controlPanel: {
        title: "Admin Dashboard",
        subtitle: "Real-time operations data summary, optimized for quick monitoring.",
        dateRange: "Date Range",
        refresh: "Refresh",
        last7Days: "Last 7 days",
        last30Days: "Last 30 days",
        last90Days: "Last 90 days",
      },
      tabs: {
        overview: "Overview",
        leads: "Leads",
        academic: "Academic",
        hr: "HR",
      },
      sections: {
        kpiOverview: "KPI Overview",
        kpiSubtitle: "System-wide key performance indicators",
        leadsAndPlacement: "Leads & Placement Test",
        leadsSubtitle: "Track recruitment effectiveness and class placement",
        academic: "Academic",
        academicSubtitle: "Attendance, assignments, leave, makeup credits",
        hr: "Human Resources",
        hrSubtitle: "Staff structure and payroll",
      },
      kpis: {
        totalStudents: "Total Students",
        activeEnrollments: "Active Enrollments",
        totalLeads: "Total Leads",
        attendanceRate: "Attendance Rate",
        conversionRate: "Conversion Rate",
        good: "Good level",
        needsImprovement: "Needs improvement",
        newLeads: "New Leads",
        enrolledLeads: "Enrolled Leads",
        submissionRate: "Submission Rate",
        gradedRate: "Graded Rate",
        leaveRequests: "Leave Requests",
        totalStaff: "Total Staff",
        teachers: "Teachers",
        management: "Management",
        admin: "Admin",
        totalPayroll: "Total Payroll",
        totalTests: "Total Tests",
        completed: "Completed",
        noShow: "No Show",
        completionRate: "Completion Rate",
      },
      charts: {
        leadsByStatus: "Leads by Status",
        attendanceStatus: "Attendance Status",
        enrollmentStatus: "Enrollment Status",
        placementTests: "Placement Tests by Status",
        leadsStatus: "Leads Status",
        attendanceDetails: "Attendance",
        homeworkProgress: "Homework Progress (Bar)",
        leaveByStatus: "Leave by Status",
        makeupCredits: "Makeup Credits by Status",
        placementCompletion: "Placement Test Completion",
        staffStructure: "Staff Structure (Bar)",
        payrollStatus: "Payroll Run Status",
        hrTrend: "HR Operations Trend",
        conversion: "Conversion",
        rate: "Rate",
        active: "Active",
      },
      metrics: {
        assigned: "Assigned",
        submitted: "Submitted",
        graded: "Graded",
        missing: "Missing",
        workingHours: "Work Hours",
        avgHours: "Avg Hours",
        payrollProcessed: "Payroll Processed",
        payrollPending: "Payroll Pending",
      },
      empty: "No data available",
      liveView: "Live view",
      loading: "Refreshing data...",
      reload: "Reload",
      students: "Students",
      leads: "Leads",
      attendance: "Attendance",
      accountant: "Accountant",
    },
    classes: {
      header: {
        title: "Class Management",
        subtitle: "Manage classes, schedules, teachers, students and track class performance",
      },
      stats: {
        totalClasses: "Total Classes",
        ongoing: "Ongoing",
        upcoming: "Upcoming",
        completed: "Completed",
        totalStudents: "Total Students",
      },
      buttons: {
        createClass: "Create New Class",
        addStudent: "Add Student",
        close: "Close",
        cancel: "Cancel",
        save: "Save Changes",
        add: "Add to Class",
        edit: "Edit",
        endClass: "End Class",
        selectAll: "Select All",
        deselectAll: "Deselect All",
        submit: "Confirm",
        deleteSchedule: "Delete Schedule",
        confirmDelete: "Confirm Delete",
      },
      form: {
        classCode: "Class Code",
        className: "Class Name",
        branch: "Branch",
        program: "Program",
        mainTeacher: "Main Teacher",
        assistantTeacher: "Assistant Teacher",
        maxCapacity: "Max Capacity",
        startDate: "Start Date",
        endDate: "End Date",
        schedule: "Schedule",
        room: "Room",
        description: "Class Description",
        status: "Status",
        requiredField: "Required field",
      },
      schedule: {
        days: "Class Days",
        time: "Time",
        customTime: "Custom Time",
        sessionsPerWeek: "Sessions/Week",
        selectDays: "Select Days",
        selectTimeSlot: "Select Time Slot",
        totalSessions: "Total Sessions",
        noSchedule: "No Schedule",
        viewSchedule: "View Schedule",
        startTime: "Start Time",
        endTime: "End Time",
        morning: "Morning (08:00 - 10:00)",
        afternoon: "Afternoon (10:00 - 12:00)",
        earlyEvening: "Early Evening (14:00 - 16:00)",
        lateEvening: "Late Evening (16:00 - 18:00)",
        night: "Night (18:00 - 20:00)",
        lateNight: "Late Night (19:30 - 21:30)",
        sessionsPerWeek2: "2 sessions/week",
        sessionsPerWeek3: "3 sessions/week",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
        sunday: "Sunday",
      },
      status: {
        active: "Ongoing",
        upcoming: "Upcoming",
        completed: "Completed",
      },
      table: {
        classCode: "Class Code",
        className: "Class Name",
        program: "Program",
        teacher: "Teacher",
        branch: "Branch",
        enrollment: "Enrollment",
        schedule: "Schedule",
        status: "Status",
        actions: "Actions",
        noClasses: "No classes found",
        search: "Search classes...",
        allStatus: "All Status",
        allTeachers: "All Teachers",
      },
      modal: {
        addStudents: "Add Students",
        selectStudents: "Select students to add to class",
        searchPlaceholder: "Search students...",
        noStudents: "No students found",
        loading: "Loading...",
        selected: "Selected",
        total: "Total",
        students: "students",
        remainingSlots: "Remaining slots",
        capacityExceeded: "Cannot select more students",
        capacityExceededDesc: "Remaining class capacity is only",
        addSuccess: "Students added successfully",
        addSuccessDesc: "Added {count} students to the class",
        addFailed: "Failed to add students",
        addFailedDesc: "Could not add: {students}",
        addError: "An error occurred while adding students. Please try again.",
        overCapacity: "Over capacity! Class will have {count} students (max {capacity})",
        capacityOK: "Selected {count} / Remaining slots: {remaining}",
      },
      validation: {
        codeRequired: "Class code is required",
        codeExists: "Class code {code} already exists",
        nameRequired: "Class name is required",
        nameExists: "Class {name} already exists",
        programRequired: "Please select a program",
        branchRequired: "Please select a branch",
        teacherRequired: "Please select a main teacher",
        assistantTeacherConflict: "Assistant teacher and main teacher cannot be the same",
        capacityRequired: "Max capacity is required",
        capacityMin: "Max capacity must be ≥ 1",
        startDateRequired: "Start date is required",
        scheduleRequired: "Schedule is required",
        roomRequired: "Room is required",
        roomConflict: "Room {room} has schedule conflict",
        sessionCountError: "Cannot calculate session count",
      },
      messages: {
        createSuccess: "Class created successfully",
        updateSuccess: "Class updated successfully",
        updateFailed: "Failed to update class",
        createFailed: "Cannot create class. Please try again.",
        deleteConfirm: "Are you sure you want to end this class?",
        endClassSuccess: "Class ended successfully",
        endClassFailed: "Cannot end class",
        invalidStatusTransition: "Cannot change class status",
        fromUpcomingToOngoing: "Cannot change status from upcoming to ongoing",
        fromOngoingToCompleted: "Cannot change status from ongoing to completed",
        error: "An error occurred. Please try again.",
      },
    },
    courses: {
      header: {
        title: "Program Management",
        subtitle: "Manage programs and courses",
      },
      buttons: {
        create: "Create New Course",
        view: "View Details",
        edit: "Edit",
        assignBranch: "Assign Branch",
        cancel: "Cancel",
        reset: "Reset",
        restore: "Restore",
        save: "Save Changes",
        close: "Close",
      },
      stats: {
        totalCourses: "Total Courses",
        active: "Active",
        totalStudents: "Total Students",
        monthlyRevenue: "Monthly Revenue",
      },
      filters: {
        branchFiltered: "Filtered by selected branch",
        search: "Search courses...",
        statusLabel: "Select Status",
        allStatus: "All Status",
        active: "Active",
        paused: "Paused",
      },
      table: {
        title: "Course List",
        courseName: "Course Name",
        duration: "Duration",
        fee: "Fee",
        branch: "Branches Using",
        status: "Status",
        actions: "Actions",
        count: "courses",
        notFound: "No courses found",
        tryFilter: "Try changing filters or create a new course",
        showing: "Showing",
        to: "to",
        outOf: "out of",
      },
      modal: {
        createTitle: "Create New Course",
        updateTitle: "Update Program",
        createSubtitle: "Program is a shared resource — assign to branches separately after creation",
        updateSubtitle: "Edit program information",
        branchLabel: "Branch",
        branchRequired: "Branch *",
        courseNameLabel: "Course Name",
        courseNameRequired: "Course Name *",
        courseNamePlaceholder: "E.g. Basic English Communication",
        programTypeLabel: "Program Type",
        programTypeDesc: "Main program is default. Can mark as supplementary or makeup, but cannot enable both at the same time.",
        supplementary: "Mark as supplementary program",
        supplementaryLabel: "Supplementary Program",
        makeup: "Mark as makeup program",
        makeupLabel: "Makeup Program",
        programTypeInfo: "Left is supplementary program, right is makeup program. If neither is selected, the system will create a main program.",
        programTypeSelected: "Current type:",
        programMain: "Main Program",
        leaveLimitTitle: "Monthly Leave Limit",
        leaveLimitDesc: "This configuration is for leave requests by program. When you change the number of leaves, only new classes created from this program will apply the new limit, while previously created classes will keep the old limit.",
        leaveLimitLabel: "Max leaves per month",
        leaveLimitPlaceholder: "E.g. 3 (leave blank if not configured)",
        leaveCurrentLimit: "Current Limit",
        saveLeaveLimit: "Save Limit",
        selectBranchPlaceholder: "Select branch",
        assignBranchTitle: "Assign Branch to Program",
        assignBranchSubtitle: "A program can be assigned to multiple branches",
        assignBranchLabel: "Select branch to assign",
      },
      validation: {
        missingInfo: "Missing Information",
        selectBranch: "Please select a branch",
        cannotBothTypes: "Program cannot be both makeup and supplementary",
        invalidLeaveLimit: "Invalid value",
        invalidLeaveValue: "Max leaves per month must be greater than 0.",
        nameRequired: "Course name is required",
        selectBranchForAssign: "Please select a branch to assign",
      },
      messages: {
        success: "Success",
        error: "Error",
        courseCreated: "Course created",
        courseUpdated: "Program updated",
        createFailed: "Cannot create program. Please try again.",
        updateFailed: "Cannot update program. Please try again.",
        toggleSuccess: "Successfully changed course status",
        toggleFailed: "Cannot change course status. Please try again.",
        notFoundDetail: "Cannot load course details.",
        leaveLimitUpdated: "Leave limit updated",
        leaveLimitUpdateNote: "Only new classes created from this program will receive the new leave limit.",
        pauseConfirm: "Confirm Pause Course",
        pauseConfirmMsg: "Are you sure you want to pause course \"{name}\"? The course will no longer be active.",
        activateConfirm: "Confirm Activate Course",
        activateConfirmMsg: "Are you sure you want to activate course \"{name}\"? The course will be active and ready to use.",
        saving: "Saving...",
        assignBranchSuccess: "Branch assigned successfully",
        assignBranchFailed: "Cannot assign branch. Please try again.",
      },
      details: {
        title: "Course Details",
        subtitle: "Detailed information about the course",
        nameLabel: "Course Name",
        descLabel: "Course Description",
        sessionsLabel: "Number of Sessions",
        tuitionLabel: "Default Tuition",
        unitPriceLabel: "Price per Session",
        branchLabel: "Branches Using Program",
        branchAssignmentsLabel: "Branches using this program",
        noBranchAssignments: "Not assigned to any branch yet",
        typeLabel: "Program Type",
        statusLabel: "Status",
        noInfo: "No information",
        noDescription: "No description",
        noBranch: "No branch",
        defaultMakeupClass: "Default Makeup Class",
      },
      status: {
        active: "Active",
        paused: "Paused",
        main: "Main Program",
        supplementary: "Supplementary Program",
        makeup: "Makeup Program",
      },
      types: {
        main: "Main",
        supplementary: "Supplementary",
        makeup: "Makeup",
      },
    },
  },
} as const;
