export const menuAdmin = {
  vi: {
    quick: {
      businessOverview: "Tổng quan kinh doanh",
      centerOverview: "Tổng quan trung tâm",
    },
    groups: {
      leads: {
        title: "Quản lý tuyển sinh",
        manageLeads: "Quản lý leads",
      },
      learning: {
        title: "Học tập",
        courses: { list: "Danh sách chương trình học" },
        tuitionPlans: { list: "Danh sách gói học" },
        discountCampaigns: { list: "Khuyến mãi đăng ký" },
        registrations: { list: "Danh sách đăng ký lớp" },
        classes: { list: "Danh sách lớp học" },
        students: { list: "Danh sách học viên" },
      },
      curriculum: {
        title: "Chương trình",
        curriculumOverview: { list: "Khung chương trình" },
        coursesSystem: { list: "Chương trình học" },
        coursesBranch: { list: "Chương trình theo chi nhánh" },
        syllabuses: { list: "Giáo trình" },
        lessonPlans: { list: "Mẫu giáo án chuẩn" },
        academicProgression: { list: "Tiến trình học thuật" },
      },
      ops: {
        title: "Vận hành",
        rooms: "Quản lý phòng học",
        schedule: "Lịch & Phân bổ",
        pauseEnrollments: "Bảo lưu học",
        fees: "Học phí & Công nợ",
        feedback: {
          title: "Feedback lớp học",
          monthlyReport: "Báo cáo theo tháng",
          sessionReport: "Báo cáo theo buổi",
        },
        documents: "Giáo án lớp",
        teachingMaterials: "Tài liệu giảng dạy",
        media: "Truyền thông & Kiểm duyệt",
        reportRequests: "Yêu cầu báo cáo",
      },
      finance: {
        title: "Tài chính",
        cashbook: "Sổ quỹ",
        payroll: "Bảng lương",
      },
      ticketing: {
        title: "Vé học & Slot",
        ticketTypes: "Loại vé học",
        slotTypes: "Loại slot buổi học",
        ticketSlotCompat: "Tương thích vé — slot",
      },
      system: {
        title: "Hệ thống",
        accounts: "Quản lý tài khoản",
        branches: "Quản lý chi nhánh",
        blogs: "Quản lý bản tin",
        faqs: "Quản lý FAQ",
        reports: "Báo cáo sự cố",
        gamification: "Nhiệm vụ & Đổi thưởng",
        notifications: "Thông báo",
        questionBank: "Ngân hàng câu hỏi",
        settings: "Cài đặt",
      },
    },
  },
  en: {
    quick: {
      businessOverview: "Business Overview",
      centerOverview: "Center Overview",
    },
    groups: {
      leads: {
        title: "Admissions",
        manageLeads: "Leads",
      },
      learning: {
        title: "Learning",
        courses: { list: "Programs" },
        tuitionPlans: { list: "Tuition Plans" },
        discountCampaigns: { list: "Registration Discounts" },
        registrations: { list: "Registrations" },
        classes: { list: "Classes" },
        students: { list: "Students" },
      },
      curriculum: {
        title: "Programs & Curriculum",
        curriculumOverview: { list: "Curriculum Overview" },
        coursesSystem: { list: "Programs" },
        coursesBranch: { list: "Branch Programs" },
        syllabuses: { list: "Syllabuses" },
        lessonPlans: { list: "Standard Lesson Templates" },
        academicProgression: { list: "Academic Progress" },
      },
      ops: {
        title: "Operations",
        rooms: "Rooms",
        schedule: "Schedule & Allocation",
        pauseEnrollments: "Enrollment Pause",
        fees: "Tuition & Receivables",
        feedback: {
          title: "Class Feedback",
          monthlyReport: "Monthly Report",
          sessionReport: "Session Report",
        },
        documents: "Class Lesson Plans",
        teachingMaterials: "Teaching Materials",
        media: "Media & Moderation",
        reportRequests: "Report Requests",
      },
      finance: {
        title: "Finance",
        cashbook: "Cashbook",
        payroll: "Payroll",
      },
      ticketing: {
        title: "Tickets & Slots",
        ticketTypes: "Ticket Types",
        slotTypes: "Session Slot Types",
        ticketSlotCompat: "Ticket-Slot Compatibility",
      },
      system: {
        title: "System",
        accounts: "Accounts",
        branches: "Branches",
        blogs: "Blogs",
        faqs: "FAQ Management",
        reports: "Incident Reports",
        gamification: "Missions & Rewards",
        notifications: "Notifications",
        questionBank: "Question Bank",
        settings: "Settings",
      },
    },
  },
} as const;
