export const menuTeacher = {
  vi: {
    items: {
      dashboard: "Tổng quan",
      profile: "Hồ sơ cá nhân",
      myClasses: "Lớp học của tôi",
      schedule: "Lịch giảng dạy",
      subjects: "Giáo án & Tài liệu",
      materials: "Kho tài liệu",
      media: "Media lớp học",
      assignments: "Bài tập & Nộp bài",
      gamification: "Nhiệm vụ & Đổi thưởng",
      attendance: "Điểm danh",
      applications: "Đơn",
      feedback: "Báo cáo",
      feedbackGroup: "Báo cáo",
      feedbackMonthly: "Báo cáo theo tháng",
      feedbackSession: "Báo cáo theo buổi",
      reportRequests: "Yêu cầu báo cáo",
      incidentReports: "Báo cáo sự cố",
      timesheet: "Công giờ & Thu nhập",
      notifications: "Thông báo",
    },
  },
  en: {
    items: {
      dashboard: "Overview",
      profile: "Profile",
      myClasses: "My Classes",
      schedule: "Teaching Schedule",
      subjects: "Lesson Plans & Materials",
      materials: "Teaching Materials",
      media: "Class Media",
      assignments: "Assignments & Submissions",
      gamification: "Missions & Rewards",
      attendance: "Attendance",
      applications: "Applications",
      feedback: "Reports & Feedback",
      feedbackGroup: "Feedback",
      feedbackMonthly: "Monthly Report",
      feedbackSession: "Session Report",
      reportRequests: "Report Requests",
      incidentReports: "Incident Reports",
      timesheet: "Timesheet & Income",
      notifications: "Notifications",
    },
  },
} as const;
