export const menuStaffManager = {
  vi: {
    items: {
      dashboard: "Dashboard",
      accounts: "Quản lý tài khoản",
      crm: "Lead / CRM",
      allocation: "Điều phối lịch/lớp/phòng",
      makeup: "Nghỉ ngắn ngày & bù",
      pauseEnrollments: "Bảo lưu học",
      lessonPlans: "Giáo án & chất lượng",
      materials: "Tài liệu giảng dạy",
      gamification: "Gamification",
      monthlyReport: "Báo cáo tháng",
      tickets: "Ticket hỗ trợ",
      notifications: "Thông báo",
      media: "Media & Album",
      studentProfiles: "Hồ sơ học sinh",
      enrollments: "Ghi danh",
      templates: "Mẫu thông báo",
    },
  },
  en: {
    items: {
      dashboard: "Dashboard",
      accounts: "Account Management",
      crm: "Leads / CRM",
      allocation: "Schedule/Class/Room Allocation",
      makeup: "Short Leave & Make-up",
      pauseEnrollments: "Enrollment Pause",
      lessonPlans: "Lesson Plans & Quality",
      materials: "Teaching Materials",
      gamification: "Gamification",
      monthlyReport: "Monthly Report",
      tickets: "Support Tickets",
      notifications: "Broadcast Notifications",
      media: "Media & Albums",
      studentProfiles: "Student Profiles",
      enrollments: "Enrollments",
      templates: "Message Templates",
    },
  },
} as const;
