export const menuAdmin = {
  vi: {
    quick: {
      businessOverview: "Tổng quan kinh doanh",
      centerOverview: "Tổng quan trung tâm",
    },
    groups: {
      leads: {
        title: "Quản lý tuyển sinh",
        manageLeads: "Quản lý leads",
      },
      learning: {
        title: "Học tập",
        courses: { list: "Danh sách chương trình học" },
        coursesSystem: { list: "Chương trình toàn hệ thống" },
        coursesBranch: { list: "Chương trình theo chi nhánh" },
        tuitionPlans: { list: "Danh sách gói học" },
        registrations: { list: "Danh sách đăng ký lớp" },
        classes: { list: "Danh sách lớp học" },
        students: { list: "Danh sách học viên" },
      },
      ops: {
        title: "Vận hành",
        rooms: "Quản lý phòng học",
        schedule: "Lịch & Phân bổ",
        pauseEnrollments: "Bảo lưu học",
        fees: "Học phí & Công nợ",
        feedback: {
          title: "Feedback lớp học",
          monthlyReport: "Báo cáo theo tháng",
          sessionReport: "Báo cáo theo buổi",
        },
        extracurricular: "Ngoại khóa & Trại hè",
        documents: "Giáo án & Tài liệu",
        teachingMaterials: "Teaching Materials",
        media: "Media & Moderation",
        reportRequests: "Yêu cầu báo cáo",
      },
      finance: {
        title: "Tài chính",
        cashbook: "Sổ quỹ",
        payroll: "Bảng lương",
      },
      system: {
        title: "Hệ thống",
        accounts: "Quản lý tài khoản",
        branches: "Quản lý chi nhánh",
        blogs: "Quản lý bản tin",
        faqs: "Quản lý FAQ",
        reports: "Báo cáo sự cố",
        gamification: "Nhiệm vụ & Đổi thưởng",
        notifications: "Thông báo",
        questionBank: "Ngân hàng câu hỏi",
        settings: "Cài đặt",
      },
    },
  },
  en: {
    quick: {
      businessOverview: "Business Overview",
      centerOverview: "Center Overview",
    },
    groups: {
      leads: {
        title: "Admissions",
        manageLeads: "Leads",
      },
      learning: {
        title: "Learning",
        courses: { list: "Programs" },
        coursesSystem: { list: "System Programs" },
        coursesBranch: { list: "Branch Programs" },
        tuitionPlans: { list: "Tuition Plans" },
        registrations: { list: "Registrations" },
        classes: { list: "Classes" },
        students: { list: "Students" },
      },
      ops: {
        title: "Operations",
        rooms: "Rooms",
        schedule: "Schedule & Allocation",
        pauseEnrollments: "Enrollment Pause",
        fees: "Tuition & Receivables",
        feedback: {
          title: "Class Feedback",
          monthlyReport: "Monthly Report",
          sessionReport: "Session Report",
        },
        extracurricular: "Extracurricular & Camps",
        documents: "Lesson Plans & Materials",
        teachingMaterials: "Teaching Materials",
        media: "Media & Moderation",
        reportRequests: "Report Requests",
      },
      finance: {
        title: "Finance",
        cashbook: "Cashbook",
        payroll: "Payroll",
      },
      system: {
        title: "System",
        accounts: "Accounts",
        branches: "Branches",
        blogs: "Blogs",
        faqs: "FAQ Management",
        reports: "Incident Reports",
        gamification: "Missions & Rewards",
        notifications: "Notifications",
        questionBank: "Question Bank",
        settings: "Settings",
      },
    },
  },
} as const;
