export const menuTeacher = {
  vi: {
    items: {
      dashboard: "Tổng quan",
      profile: "Hồ sơ cá nhân",
      myClasses: "Lớp học của tôi",
      schedule: "Lịch giảng dạy",
      subjects: "Giáo án & Tài liệu",
      materials: "Kho tài liệu",
      assignments: "Bài tập & Nộp bài",
      gamification: "Gamification",
      attendance: "Điểm danh",
      applications: "Đơn",
      feedback: "Báo cáo & Feedback",
      reportRequests: "Yêu cầu báo cáo",
      timesheet: "Công giờ & Thu nhập",
      notifications: "Thông báo",
    },
  },
  en: {
    items: {
      dashboard: "Overview",
      profile: "Profile",
      myClasses: "My Classes",
      schedule: "Teaching Schedule",
      subjects: "Lesson Plans & Materials",
      materials: "Teaching Materials",
      assignments: "Assignments & Submissions",
      gamification: "Gamification",
      attendance: "Attendance",
      applications: "Applications",
      feedback: "Reports & Feedback",
      reportRequests: "Report Requests",
      timesheet: "Timesheet & Income",
      notifications: "Notifications",
    },
  },
} as const;
