
export const menuStaffManager = {
  vi: {
    items: {
      dashboard: "Dashboard",
      accounts: "Quản lý tài khoản",
      crm: "Tuyển sinh",
      allocation: "Điều phối lịch/lớp/phòng",
      makeup: "Nghỉ ngắn ngày & bù",
      pauseEnrollments: "Bảo lưu học",
      lessonPlans: "Giáo án & chất lượng",
      materials: "Tài liệu giảng dạy",
      gamification: "Nhiệm vụ & Đổi thưởng",
      reports: "Báo cáo",
      monthlyReport: "Báo cáo theo tháng",
      sessionReport: "Báo cáo theo buổi",
      tickets: "Ticket hỗ trợ",
      incidentReports: "Báo cáo sự cố",
      notifications: "Thông báo",
      media: "Media & Album",
      studentProfiles: "Hồ sơ học sinh",
      enrollments: "Ghi danh",
      templates: "Mẫu thông báo",
      profile: "Hồ sơ cá nhân",
    },
  },
  en: {
    items: {
      dashboard: "Dashboard",
      accounts: "Account Management",
      crm: "Leads / CRM",
      allocation: "Schedule/Class/Room Allocation",
      makeup: "Short Leave & Make-up",
      pauseEnrollments: "Enrollment Pause",
      lessonPlans: "Lesson Plans & Quality",
      materials: "Teaching Materials",
      gamification: "Missions & Rewards",
      reports: "Reports",
      monthlyReport: "Monthly Report",
      sessionReport: "Session Report",
      tickets: "Support Tickets",
      incidentReports: "Incident Reports",
      notifications: "Broadcast Notifications",
      media: "Media & Albums",
      studentProfiles: "Student Profiles",
      enrollments: "Enrollments",
      templates: "Message Templates",
      profile: "My Profile",
    },
  },
} as const;
